# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Adventures in Computing
tagline:             'Musings of a mutant Computer Scientist that somehow got to do IT'
description:         'Random notes about technicalities, or deeper observations about the practices of CS, IT and AI'
url:                 https://jflamy.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jean-François Lamy
  url:               https://linkedin.com/jflamy
  email:             jf@jflamy.dev

# Custom vars
version:             1.0.1

theme: jekyll-theme-tactile